color: null
fieldLayouts:
  cb2c60d4-7ec1-43e1-a50c-11373c2163cb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-13T09:56:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9a2d582d-c384-45bb-8dad-26bfb1e1a056
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-13T09:58:31+00:00'
            elementCondition: null
            fieldUid: d7380970-42a0-4ec7-a316-3c598543fe40 # Hide
            handle: null
            includeInCards: false
            instructions: null
            label: 'Hide in navigation'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b74e2b5-db6b-4a21-a39d-91ba680fb5c6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-13T09:57:56+00:00'
            elementCondition: null
            fieldUid: 0a0a61db-c42b-49a9-b6cd-9a96be13752e # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11d6398f-e859-4dee-b4f8-5db14b42f509
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-01-13T09:57:56+00:00'
            elementCondition: null
            fieldUid: 381ca719-b0cc-4bba-9b7d-4f65f18f781f # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee9ba273-f39a-444c-9711-d5b9ae1ee1d3
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-01-13T10:21:46+00:00'
            elementCondition: null
            fieldUid: 19da515d-1f1d-4979-bad0-42556b9f0b78 # Align
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75bd3443-358b-40ef-ad6f-c02ca3cba6a6
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-01-13T09:57:56+00:00'
            elementCondition: null
            fieldUid: 02a30bda-d2b5-41f6-ba9b-8ce888e8e6ae # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91c52b86-8511-48d4-be77-d23252297946
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6a7bb75f-6801-4913-aa57-e120826b2a2e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-13T09:57:56+00:00'
            elementCondition: null
            fieldUid: b9c4f964-3733-467b-b83e-e3802aa7b65f # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc7c919e-a136-4438-bf07-4a4957b47cfc
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 2e520c4b-4aa7-4d3d-a195-eb1453a77d13
        userCondition: null
handle: page
hasTitleField: true
icon: null
name: Page
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
