columnSuffix: null
handle: heroStyle
instructions: 'Use this to choose a full hero image with overlay or two column hero layout'
name: 'Hero style'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Full hero'
        -
          - value
          - fullHero
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Two column'
        -
          - value
          - twoColumn
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
